# Generated by Django 4.2 on 2025-08-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="account",
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.CharField(
                default="Unknown", max_length=15, verbose_name="Account"
            ),
        ),
    ]
