# Generated by Django 4.2 on 2025-08-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_remove_customer_account_transaction_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.CharField(max_length=15, unique=True, verbose_name="Account"),
        ),
    ]
