# Generated by Django 4.2 on 2025-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0005_alter_transaction_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer",
            field=models.CharField(max_length=20),
        ),
    ]
